##### [Visualizar online](https://docs.google.com/spreadsheets/d/1Hx1-aAWYVGLFYoR_cd_XaByp_61dk_pW0RC3kCMpBQw/edit?usp=sharing)

In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv('../data/metaheuristics_dataset.csv', sep=';', index_col=False, dtype=str).fillna('').astype(str)

In [3]:
def round_3(value):
    return round(value, 3)

In [4]:
def type_float(value):
    if(value == ''):
        return ''
    else:
        return float(value)

In [5]:
def type_float_round_3(value):
    if(value == ''):
        return ''
    else:
        return round_3(float(value))

In [6]:
dataframe['Iterations'] = dataframe['Iterations'].astype(int)
dataframe['Average cost'] = dataframe['Average cost'].astype(float).apply(round_3)
dataframe['Best cost'] = dataframe['Best cost'].astype(int)
dataframe['Average performance time(s)'] = dataframe['Average performance time(s)'].apply(type_float)
dataframe['Best performance time(s)'] = dataframe['Best performance time(s)'].astype(float)
dataframe['GAP(%)'] = dataframe['GAP(%)'].astype(float).apply(round_3)
dataframe['Average GAP(%)'] = dataframe['Average GAP(%)'].apply(type_float_round_3)

In [7]:
dataframe

,Instance,Heuristic,Iterations,Average cost,Best cost,Average performance time(s),Best performance time(s),GAP(%),Average GAP(%)
0,n3m10A,Initial solution,1,24861.000,24861,,0.000084,232.233,
1,n3m10A,GREEDY,1,16060.000,16060,,3.251179,114.620,
2,n3m10A,VND,5,15046.857,8940,0.000175,0.000421,19.471,101.081
3,n3m10A,ILS,501,11614.176,7483,0.173473,0.173504,0.000,55.207
4,n3m10A,GRASP,500,7483.000,7483,,116.101535,0.000,
...,...,...,...,...,...,...,...,...,...
115,n5m50E,GREEDY,1,120735.000,120735,,0.000184,587.479,
116,n5m50E,VND,6,46097.241,30114,0.000201,0.000322,71.472,162.483
117,n5m50E,ILS,501,46517.344,30114,0.213804,0.223197,71.472,164.875
118,n5m50E,GRASP,500,180252.000,180252,,276.219539,926.375,
119,n5m50E,VNS,802,38795.033,17562,0.083846,0.129430,0.000,120.903

In [8]:
dataframe[dataframe['GAP(%)'] == 0].reset_index(drop=True)

,Instance,Heuristic,Iterations,Average cost,Best cost,Average performance time(s),Best performance time(s),GAP(%),Average GAP(%)
0,n3m10A,ILS,501,11614.176,7483,0.173473,0.173504,0.0,55.207
1,n3m10A,GRASP,500,7483.000,7483,,116.101535,0.0,
2,n3m10A,VNS,665,11655.636,7483,0.076838,0.094233,0.0,55.762
3,n3m10B,VND,5,4022.500,1277,0.000183,0.000274,0.0,214.996
4,n3m10B,ILS,760,3276.467,1277,0.175711,0.252196,0.0,156.575
5,n3m10B,GRASP,500,1277.000,1277,,104.496612,0.0,
6,n3m10B,VNS,522,2714.222,1277,0.074217,0.076181,0.0,112.547
7,n3m10C,VND,5,5523.385,2088,0.000176,0.000239,0.0,164.53
8,n3m10C,ILS,502,4962.375,2088,0.167879,0.161764,0.0,137.662
9,n3m10C,GRASP,500,2088.000,2088,,104.094084,0.0,
10,n3m10C,VNS,553,4109.222,2088,0.069214,0.076264,0.0,96.802
11,n3m10D,ILS,799,2391.278,322,0.21049,0.348730,0.0,642.633
12,n3m10D,GRASP,500,322.000,322,,101.875424,0.0,
13,n3m10D,VNS,553,2299.625,322,0.088548,0.076264,0.0,614.169
14,n3m10E,VND,5,4086.778,3343,0.000221,0.000363,0.0,22.249
15,n3m10E,ILS,727,3920.600,3343,0.215449,0.354705,0.0,17.278
16,n3m10E,GRASP,500,3343.000,3343,,124.942495,0.0,
17,n3m10E,VNS,733,3882.375,3343,0.087482,0.125397,0.0,16.134
18,n3m20A,VND,5,54609.415,32373,0.000211,0.000250,0.0,68.688
19,n3m20A,ILS,501,53866.519,32373,0.216407,0.211152,0.0,66.393
20,n3m20A,VNS,1890,51576.317,32373,0.088215,0.316873,0.0,59.319
21,n3m20B,VNS,552,31430.862,18823,0.08896,0.089147,0.0,66.981
22,n3m20C,VNS,1806,15890.565,8968,0.083935,0.303288,0.0,77.192
23,n3m20D,VNS,897,9572.346,5011,0.074819,0.122276,0.0,91.027
24,n3m20E,VNS,828,15719.474,5061,0.065622,0.111138,0.0,210.6
25,n3m40A,VNS,983,112715.197,67124,0.072144,0.129848,0.0,67.921
26,n3m40B,VNS,942,106165.378,45376,0.073301,0.123092,0.0,133.968
27,n3m40C,VNS,514,111765.077,71650,0.070612,0.076969,0.0,55.988
28,n3m40D,VNS,833,51617.632,20803,0.075835,0.112640,0.0,148.126
29,n3m40E,VNS,1118,43279.423,25551,0.067352,0.152169,0.0,69.384
30,n5m50A,VNS,990,161610.086,92891,0.083169,0.153392,0.0,73.978
31,n5m50B,VNS,872,100078.976,51137,0.083258,0.134862,0.0,95.708
32,n5m50C,VNS,800,70093.516,25540,0.078208,0.129358,0.0,174.446
33,n5m50D,VNS,1098,50974.586,22966,0.082912,0.175798,0.0,121.957
34,n5m50E,VNS,802,38795.033,17562,0.083846,0.129430,0.0,120.903